services:
  db:
    image: postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET_KEY
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
    depends_on:
      - db
    command: npm start
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
