version: "3"
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=authdb
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - JWT_SECRET=kudaliar
      - ACCESS_TOKEN_SECRET=kudaliar
    depends_on:
      - db
    command: npm start
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
